apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          # to test if the env got the values un comment below
          # and kubectl logs $podname
          # command: ['sh', '-c', 'echo "users: $LDAP_USERS" "passwords: $LDAP_PASSWORDS"']
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap-secret
                  key: adminpassword
            - name: LDAP_USERS
              valueFrom:
                secretKeyRef:
                  name: openldap-secret
                  key: users
            - name: LDAP_PASSWORDS
              valueFrom:
                secretKeyRef:
                  name: openldap-secret
                  key: passwords
          ports:
            - name: tcp-ldap
              containerPort: 1389
          resources:
            requests:
              cpu: '0.5m'
              memory: '512Mi'
            limits:
              cpu: '1m'
              memory: '1024Mi'

---

apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 1389
      targetPort: 1389
  selector:
    app.kubernetes.io/name: openldap